Repository EstSoftOrmi3FinalProject/SchoolTalks-Frontend, pull requests merged in 2023-12, with the labels that each got.

#4 :sparkles: 기존 오류수정 및 로그아웃 추가
  assets/css/main.css
  assets/js/logout.js
  assets/js/main.js
  assets/js/register.js
  chat/index.html
  cover.html
  login.html
  post/index.html
  profile.html
  qna.html
  register.html
  study/study-index.html
Labels: enhancement

#8 Fix/html include
  .vscode/settings.json
  assets/js/bootstrap.min.js
  assets/js/count-up.min.js
  assets/js/glightbox.min.js
  assets/js/include.js
  assets/js/jquery-counterup.min.js
  assets/js/logout.js
  assets/js/main.js
  assets/js/tiny-slider.js
  assets/js/wow.min.js
  chat/index.html
  cover.html
  header.html
  login.html
  post/index.html
  profile.html
  qna.html
  register.html
  study/create-post.html
  study/post.html
  study/study-index.html
Labels: help wanted

#15 ♻️ 주소 및 판별식 수정
  assets/js/include.js
  header.html
Labels: bug

#31 26 fe 자유게시판 댓글 수정삭제 및 자잘한 기능추가
  assets/css/post/btn.css
  assets/css/post/comment.css
  assets/js/chat.js
  assets/js/include.js
  assets/js/post/post.js
  assets/js/post/write.js
  header.html
  index.html
Labels: enhancement

#39 ♻️ Ai Chat 채팅 말풍선 수정
  assets/css/gpt.css
  assets/js/gpt/chat.js
  gpt/index.html
Labels: enhancement

#41 38 fe ai chat css 및 js 수정
  assets/css/gpt.css
  assets/images/gpt/channels4_profile.jpg
  assets/js/gpt/chat.js
  gpt/index.html
Labels: enhancement

#69 FE- study 부분 fix
  assets/css/study/post.css
  assets/js/post/post-comment.js
  assets/js/post/post.js
  assets/js/post/write.js
  assets/js/study/study-post-pk-like.js
  assets/js/study/study-post-pk.js
  assets/js/study/study-post.js
  study/post.html
Labels: bug
